### ISSUE TITLE
db dumptime GMT --> EST?

### ISSUE THREAD

**Issue by swbae31** [adicu/density#40]
Wouldn't it be better to store all time data in the db in EST?

**Comment by natebrennand** [comment]
can this be closed? @jzf2101

**Comment by jzf2101** [comment]
I don't think so.  We're still listing the data as being in GMT when it's in Eastern:
```
{
  "data": [
    {
      "client_count": 698, 
      "dump_time": "Mon, 02 Mar 2015 13:00:00 GMT", 
      "group_id": 23, 
      "group_name": "Uris/Watson Library", 
      "parent_id": 2, 
      "parent_name": "Uris"
    }, 
```

**Comment by natebrennand** [comment]
So I set the TZ to EST when inserting (https://github.com/adicu/wireless_data_processor/blob/master/main.go#L44).
And changing the cursor's TZ doesn't appear to affect this, so I'm not sure what we can do.

The schema does not have a TZ associated with the datetimes so this seems to be a psycopg2 issue that it assigns a GMT TZ automatically. I don't think that the API should be returning times that have a TZ associated with it because all of the values will always be EST.

**Comment by jzf2101** [comment]
See #84

**Comment by natebrennand** [comment]
I'm just going to resolve this entire deal today or tomorrow. This should've been implemented a while ago
